/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 *
 * Name 1: 			Eugen Burikov
 * Name 2:			Dennis Zubiks
 * Gruppennummer: 	15
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define LED_RED 0
#define LED_ORA 1
#define LED_GRE 2

#include <stddef.h>
#include <stdint.h>

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"


GPIO_Handle_t GpioLed_red;
GPIO_Handle_t GpioLed_green;
GPIO_Handle_t GpioLed_orange;
GPIO_Handle_t GpioBtn;
uint16_t state;

void delay(int s) {
	for(volatile uint32_t i = 0; i < s * 1000000; i++);
}

void toggleLEDs(){
	GPIO_ToggleOutputPin(&GpioLed_red);
	GPIO_ToggleOutputPin(&GpioLed_green);
	GPIO_ToggleOutputPin(&GpioLed_orange);
}

void toggleLED(int led){
	switch (led){
	case 0:
		GPIO_ToggleOutputPin(&GpioLed_red);
		break;
	case 1:
		GPIO_ToggleOutputPin(&GpioLed_orange);
		break;
	case 2:
		GPIO_ToggleOutputPin(&GpioLed_green);
		break;
	}

}

void initLedPins(){

	memset( &GpioLed_red,0,sizeof(GpioLed_red));
	memset( &GpioLed_green,0,sizeof(GpioLed_green));
	memset( &GpioLed_orange,0,sizeof(GpioLed_orange));

	GpioLed_red.pGPIOx = GPIOD;
	GpioLed_red.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
	GpioLed_red.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GpioLed_green.pGPIOx = GPIOD;
	GpioLed_green.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_11;
	GpioLed_green.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GpioLed_orange.pGPIOx = GPIOD;
	GpioLed_orange.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_10;
	GpioLed_orange.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GPIO_Init(&GpioLed_red);
	GPIO_Init(&GpioLed_green);
	GPIO_Init(&GpioLed_orange);

	GPIO_WriteToOutputPin(&GpioLed_red, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GpioLed_green, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GpioLed_orange, GPIO_PIN_RESET);

}

void traffic_light(){
	turn_led_off();
	toggleLED(LED_RED);
	delay(5);
	toggleLED(LED_ORA);
	delay(5);
	toggleLEDs();
	delay(5);
	toggleLED(LED_GRE);
	toggleLED(LED_ORA);
	delay(5);
	toggleLED(LED_ORA);

}

void turn_led_off(){
	GPIO_WriteToOutputPin(&GpioLed_red, DISABLE);
	GPIO_WriteToOutputPin(&GpioLed_green, DISABLE);
	GPIO_WriteToOutputPin(&GpioLed_orange, DISABLE);
}

void initButton(){
	memset(&GpioBtn,0,sizeof(GpioBtn));
	GpioBtn.pGPIOx = GPIOD;
	GpioBtn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioBtn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;
	GpioBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PIN_PU;
	GPIO_Init(&GpioBtn);
}

int main(void)
{
	//Enable Clock
	GPIO_PeriClockControl(GPIOD, ENABLE);
	SYSCFG_PCLK_EN();

	initLedPins();
	initButton();

	//IRQ config
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);

	while(1){
		traffic_light();
	}
}

void EXTI9_5_IRQHandler(void){
	// save state
	state = GPIO_ReadFromInputPort(GpioBtn.pGPIOx);
	turn_led_off();
	toggleLED(LED_RED);
	delay(7);
	// return state
	GPIO_WriteToOutputPort(GpioBtn.pGPIOx, state);
	GPIO_IRQHandling(GPIO_PIN_NO_5);
}
