/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stddef.h>
#include <stdint.h>

#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"


GPIO_Handle_t GpioLed_red;
GPIO_Handle_t GpioLed_green;
GPIO_Handle_t GpioLed_orange;

void delay(void) {
	for(volatile uint32_t i = 0; i < 500000; i++);
}

void delay_ms(int ms) {
	int multiplicator = 16000;
	int res = ms * multiplicator;
	for(volatile uint32_t c = 0; c < res; c++);

}

void toggleLED(){
	GPIO_ToggleOutputPin(&GpioLed_red);
	GPIO_ToggleOutputPin(&GpioLed_green);
	GPIO_ToggleOutputPin(&GpioLed_orange);
}

void initLedPins(){
	GpioLed_red.pGPIOx = GPIOD;
	GpioLed_red.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_14;
	GpioLed_red.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GpioLed_green.pGPIOx = GPIOD;
	GpioLed_green.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed_green.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GpioLed_orange.pGPIOx = GPIOD;
	GpioLed_orange.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GpioLed_orange.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;

	GPIO_Init(&GpioLed_red);
	GPIO_Init(&GpioLed_green);
	GPIO_Init(&GpioLed_orange);

	GPIO_WriteToOutputPin(&GpioLed_red, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GpioLed_green, GPIO_PIN_RESET);
	GPIO_WriteToOutputPin(&GpioLed_orange, GPIO_PIN_RESET);

}

int main(void)
{
	initLedPins();

	while(1){
		toggleLED();
		delay_ms(300);
	}
}
